### ISSUE TITLE
Always throws HTTPError 403 Forbidden.

### ISSUE THREAD

**Issue by roccomuso** [kevva/instagram-user#3]
```
{ HTTPError: Response code 403 (Forbidden)
    at stream.catch.then.data (/home/instagram-test/node_modules/got/index.js:123:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  message: 'Response code 403 (Forbidden)',
  host: 'instagram.com',
  hostname: 'instagram.com',
  method: 'GET',
  path: '/ecooltra/?__a=1',
  statusCode: 403,
  statusMessage: 'Forbidden' }
```

**Comment by keeganjk** [comment]
Same
